### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Justinzobel/surt#2]
Warning:
* All items in the Solus User Repo are used at your own risk.
* Templates are created by Solus users and have NOT been tested.
Notice: Checking evobuild initialised.
Traceback (most recent call last):
  File "/usr/bin/evobuild", line 21, in <module>
    import yaml
ImportError: No module named yaml
Notice: Checking evobuild up to date.
Traceback (most recent call last):
  File "/usr/bin/evobuild", line 21, in <module>
    import yaml
ImportError: No module named yaml
Notice: Attempting download of vivaldi template, this should only take a moment.
Notice: Template found, building package.
Traceback (most recent call last):
  File "/usr/bin/evobuild", line 21, in <module>
    import yaml
ImportError: No module named yaml
Error: Build failed

**Comment by bil-elmoussaoui** [comment]
Ok i figured out that i had to install python-yaml. please add that as a dependency in the readme file
and i have a new issue when i try to install any new software
bilalroot@Leonovo ~ $ sudo ur install vivaldi
Mot de passe :
Warning:
* All items in the Solus User Repo are used at your own risk.
* Templates are created by Solus users and have NOT been tested.
Notice: Checking evobuild initialised.
unstable-x86_64 is already initialised
Notice: Checking evobuild up to date.
Copied host eopkg.conf
Removing stale d-bus file
Mise à jour des dépôts
Mise à jour du dépôt : Solus
eopkg-index.xml.xz.sha1sum     (40.0  B)100%    952.56 KB/s [00:00:00] [fini]
les informations concernant le dépôt Solus sont à jour.
Pas de paquet à mettre à jour.
Update succeeded
Les paquets suivants sont déjà installés et ne seront pas installés à nouveau :
autoconf             automake                     bash-completion-devel
binutils             bison                        bzip2-devel          
catbox               clang                        cmake                
curl-devel           db5-devel                    dbus-devel           
dbus-glib-devel      diffstat                     diffutils            
expat-devel          file-devel                   flex                 
flex-devel           fontconfig-devel             g++                  
gcc                  gdbm-devel                   gettext-devel        
gfortran             glib2-devel                  glibc-devel          
gmp-devel            gobject-introspection-devel  gpm-devel            
inotify-tools-devel  intltool                     kernel-libc-devel    
libarchive-bin       libarchive-devel             libffi-devel         
libgcrypt-devel      libgusb-devel                libnspr-devel        
libpcre-devel        libpipeline-devel            libtool-devel        
libxml2-devel        libxslt-devel                m4                   
make                 mpc-devel                    mpfr-devel           
nasm                 ncurses-devel                openssl-devel        
pam-devel            patch                        pciutils-devel       
perl-xmlparser       pkg-config                   polkit-devel         
popt-devel           procps-ng-devel              python-dbus-devel    
quilt                readline-devel               spidermonkey-devel   
systemd-devel        util-linux-devel             wireless-tools-devel 
xz-devel             ypkg                         zlib-devel           
Aucun paquet à installer.
Devel update complete
Killing d-bus pid: 5472
umounting /var/lib/evobuild/roots/unstable-x86_64/dev/pts
umounting /var/lib/evobuild/roots/unstable-x86_64/proc
umounting /var/lib/evobuild/roots/unstable-x86_64/sys
umounting /var/lib/evobuild/roots/unstable-x86_64/var/cache/eopkg/packages
Umounting bind-mount /dev
Notice: Attempting download of vivaldi template, this should only take a moment.
Notice: Template found, building package.
Building vivaldi for unstable-x86_64
Copied host eopkg.conf
Removing stale d-bus file
Mise à jour des dépôts
Mise à jour du dépôt : Solus
eopkg-index.xml.xz.sha1sum     (40.0  B)100%      0.98 MB/s [00:00:00] [fini]
les informations concernant le dépôt Solus sont à jour.
Pas de paquet à mettre à jour.
Update succeeded
Les paquets suivants sont déjà installés et ne seront pas installés à nouveau :
autoconf             automake                     bash-completion-devel
binutils             bison                        bzip2-devel          
catbox               clang                        cmake                
curl-devel           db5-devel                    dbus-devel           
dbus-glib-devel      diffstat                     diffutils            
expat-devel          file-devel                   flex                 
flex-devel           fontconfig-devel             g++                  
gcc                  gdbm-devel                   gettext-devel        
gfortran             glib2-devel                  glibc-devel          
gmp-devel            gobject-introspection-devel  gpm-devel            
inotify-tools-devel  intltool                     kernel-libc-devel    
libarchive-bin       libarchive-devel             libffi-devel         
libgcrypt-devel      libgusb-devel                libnspr-devel        
libpcre-devel        libpipeline-devel            libtool-devel        
libxml2-devel        libxslt-devel                m4                   
make                 mpc-devel                    mpfr-devel           
nasm                 ncurses-devel                openssl-devel        
pam-devel            patch                        pciutils-devel       
perl-xmlparser       pkg-config                   polkit-devel         
popt-devel           procps-ng-devel              python-dbus-devel    
quilt                readline-devel               spidermonkey-devel   
systemd-devel        util-linux-devel             wireless-tools-devel 
xz-devel             ypkg                         zlib-devel           
Aucun paquet à installer.
Devel update complete
--2015-11-02 11:39:41--  http://solus-us.tk/sources/a0f8b529631b0eb36e359289ecafc2d681fcf53bf149e29ee781b6f4df1748df/vivaldi_TP4.1.0.219.50-1_amd64.deb
Résolution de solus-us.tk… 107.191.125.26
Connexion à solus-us.tk|107.191.125.26|:80… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 40733876 (39M) [application/x-debian-package]
Sauvegarde en : « /var/cache/eopkg/archives/vivaldi_TP4.1.0.219.50-1_amd64.deb »

/var/cache/eopkg/ar 100%[=====================>]  38,85M  1,88MB/s   ds 44s    

2015-11-02 11:40:26 (907 KB/s) — « /var/cache/eopkg/archives/vivaldi_TP4.1.0.219.50-1_amd64.deb » sauvegardé [40733876/40733876]

building vivaldi
Running install...
+ export TERM=dumb
+ TERM=dumb
+ cd /var/ypkg-root/build/vivaldi
+ export 'CFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error'
+ CFLAGS='-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error'
+ export 'CXXFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error'
+ CXXFLAGS='-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fomit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error'
+ export 'LDFLAGS=-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now'
+ LDFLAGS='-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now'
+ export CC=x86_64-solus-linux-gcc
+ CC=x86_64-solus-linux-gcc
+ export CXX=x86_64-solus-linux-g++
+ CXX=x86_64-solus-linux-g++
+ export PATH=/usr/bin:/bin
+ PATH=/usr/bin:/bin
+ export srcdir=/var/ypkg-root/build/vivaldi
+ srcdir=/var/ypkg-root/build/vivaldi
+ export installdir=/var/ypkg-root/install/vivaldi
+ installdir=/var/ypkg-root/install/vivaldi
+ export package=vivaldi
+ package=vivaldi
+ export release=2
+ release=2
+ export version=4.1.0.219.50
+ version=4.1.0.219.50
+ export sources=/var/cache/eopkg/archives
+ sources=/var/cache/eopkg/archives
+ export LD_AS_NEEDED=1
+ LD_AS_NEEDED=1
+ export CCACHE_DIR=/root/.ccache
+ CCACHE_DIR=/root/.ccache
+ ar xv /var/cache/eopkg/archives/vivaldi_TP4.1.0.219.50-1_amd64.deb
x - debian-binary
x - control.tar.gz
x - data.tar.xz
x - _gpgbuilder
+ tar xf data.tar.xz
+ mkdir -p /var/ypkg-root/install/vivaldi/usr
+ rm -r opt/vivaldi/cron
+ rm -r etc
+ rm -r usr/share/xfce4
+ rm -r usr/share/doc/vivaldi
+ cp -r usr /var/ypkg-root/install/vivaldi
+ cp -r opt /var/ypkg-root/install/vivaldi
+ '[' -f /var/ypkg-root/install/vivaldi/usr/share/man/dir ']'
+ xargs rm -rf
+ find /var/ypkg-root/install/vivaldi//usr/lib64 -type f -name '*.la'
find: "/var/ypkg-root/install/vivaldi//usr/lib64": Aucun fichier ou dossier de ce type
vivaldi
Programme terminé.
PISI.source.packager.email: Item Email obligatoire non disponible
autoxml.read : Le fichier '/var/ypkg-root/vivaldi.xml' contient des erreurs
Veuillez utiliser 'pisi help' pour une aide généraliste.
Failed to build package
Return code was 256
Build failed
Killing d-bus pid: 5504
umounting /var/cache/evobuild/vivaldi/union/dev/pts
umounting /var/cache/evobuild/vivaldi/union/proc
umounting /var/cache/evobuild/vivaldi/union/sys
umounting /var/cache/evobuild/vivaldi/union/var/cache/eopkg/archives
umounting /var/cache/evobuild/vivaldi/union/root/.ccache
umounting /var/cache/evobuild/vivaldi/union/var/cache/eopkg/packages
Umounting bind-mount /dev
Error: Build failed

**Comment by Justinzobel** [comment]
Updated README, please pull the latest UR as seen in the instructions and try again, I re-enabled the packager file check now.

**Comment by bil-elmoussaoui** [comment]
Thanks, when i first used the script i forget to add my mail and i receive this as an error message, how can i fix it 
PISI.source.packager.email: Item Email obligatoire non disponible

**Comment by Justinzobel** [comment]
gedit ~/.solus/packager
